"""Case folder layout and path resolution.

Each case lives under ``live/cases/<name>/`` with identical files:

  intake.json   — participant forms + tree config (source)
  session.json  — psychology profiles (generated by demo_intake)
  simulated_conversation_tree.json  — conversation tree (generated by demo_conversation)
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from mediation.intake import IntakeForm, PreparedSession

CASES_DIR = Path(__file__).resolve().parent / "cases"
INTAKE_FILE = "intake.json"
SESSION_FILE = "session.json"
TREE_FILE = "simulated_conversation_tree.json"
TEMPLATE_DIR = "_template"


class MediationCase:
    """One mediation case directory with a fixed file layout."""

    def __init__(self, path: Path, *, name: str | None = None) -> None:
        self.path = path.resolve()
        self.name = name or self.path.name

    @property
    def intake_path(self) -> Path:
        return self.path / INTAKE_FILE

    @property
    def session_path(self) -> Path:
        return self.path / SESSION_FILE

    @property
    def tree_path(self) -> Path:
        return self.path / TREE_FILE

    def load_intake(self) -> IntakeForm:
        return IntakeForm.from_json_file(self.intake_path)

    def load_session(self) -> PreparedSession:
        return PreparedSession.from_json_file(self.session_path)

    def ensure_dir(self) -> Path:
        self.path.mkdir(parents=True, exist_ok=True)
        return self.path

    @classmethod
    def resolve(cls, case: str | Path, *, cases_root: Path = CASES_DIR) -> MediationCase:
        """Resolve a case name or path to a ``MediationCase``."""
        raw = Path(case)
        if raw.is_absolute() or raw.parent != Path("."):
            candidate = raw.resolve()
        else:
            candidate = (cases_root / raw).resolve()

        intake_path = candidate / INTAKE_FILE
        if not intake_path.is_file():
            raise FileNotFoundError(
                f"Case not found: {candidate}\n"
                f"Expected {INTAKE_FILE} at {intake_path}\n"
                f"Available: {', '.join(list_cases()) or '(none)'}"
            )
        return cls(candidate)

    @classmethod
    def list_cases(cls, *, cases_root: Path = CASES_DIR) -> list[str]:
        if not cases_root.is_dir():
            return []
        names: list[str] = []
        for entry in sorted(cases_root.iterdir()):
            if not entry.is_dir():
                continue
            if entry.name.startswith("_"):
                continue
            if (entry / INTAKE_FILE).is_file():
                names.append(entry.name)
        return names

    @classmethod
    def create_from_template(
        cls,
        name: str,
        *,
        cases_root: Path = CASES_DIR,
    ) -> MediationCase:
        if not name or name.startswith("_"):
            raise ValueError(f"Invalid case name: {name!r}")

        template_dir = cases_root / TEMPLATE_DIR
        template_intake = template_dir / INTAKE_FILE
        if not template_intake.is_file():
            raise FileNotFoundError(f"Missing template: {template_intake}")

        target = cases_root / name
        if target.exists():
            raise FileExistsError(f"Case already exists: {target}")

        target.mkdir(parents=True)
        shutil.copy2(template_intake, target / INTAKE_FILE)
        return cls(target)


def list_cases(*, cases_root: Path = CASES_DIR) -> list[str]:
    return MediationCase.list_cases(cases_root=cases_root)


def resolve_tree_path(
    *,
    case: str | Path | None = None,
    tree: str | Path | None = None,
    repo_root: Path | None = None,
) -> tuple[Path, str | None]:
    """
    Resolve a conversation tree JSON from CLI flags or environment.

    Priority: ``tree`` > ``case`` > ``MEDIATION_TREE_PATH`` > ``MEDIATION_CASE`` > case1
    Returns ``(tree_path, case_name)``.
    """
    root = repo_root or Path(__file__).resolve().parents[1]

    if tree:
        path = Path(tree)
        if not path.is_absolute():
            path = root / path
        return path.resolve(), _case_name_from_tree(path)

    case_name = str(case).strip() if case else os.getenv("MEDIATION_CASE", "").strip() or None
    if case_name:
        mediation_case = MediationCase.resolve(case_name)
        return mediation_case.tree_path, mediation_case.name

    env_tree = os.getenv("MEDIATION_TREE_PATH", "").strip()
    if env_tree:
        path = Path(env_tree)
        if not path.is_absolute():
            path = root / path
        path = path.resolve()
        return path, _case_name_from_tree(path)

    default = CASES_DIR / "case1" / TREE_FILE
    return default, "case1"


def _case_name_from_tree(tree_path: Path) -> str | None:
    """Return case folder name when tree lives under ``live/cases/<name>/``."""
    parent = tree_path.resolve().parent
    if parent.parent.name == "cases":
        return parent.name
    return None
