"""Systematic prompt templates (see subdirectories for source files)."""

from .registry import (
    AGENT_MEDIATED_RESPONSE,
    AGENT_OPENING,
    MEDIATOR_INITIAL,
    MEDIATOR_PEER,
    MEDIATOR_STYLES,
    MEDIATOR_STYLE_LABELS,
    MEDIATOR_TRANSITION,
    MEDIATION_TOOLS,
    OPENING_STRATEGIES,
    OPENING_STRATEGY_LABELS,
    PSYCHOLOGY_ANALYZE,
    PSYCHOLOGY_SYSTEM,
    EVALUATION_EVALUATE,
    EVALUATION_SYSTEM,
    SCENARIO_PROMPTS,
    MediatorStyle,
    format_initial_intervention,
    format_peer_intervention,
    format_transition,
    pick_scenario,
    pick_scenario_optional,
    pick_tool,
    pick_tool_optional,
    perspective_summary,
    style_instruction,
)

__all__ = [
    "AGENT_MEDIATED_RESPONSE",
    "AGENT_OPENING",
    "MEDIATOR_INITIAL",
    "MEDIATOR_PEER",
    "MEDIATOR_STYLES",
    "MEDIATOR_STYLE_LABELS",
    "MEDIATOR_TRANSITION",
    "MEDIATION_TOOLS",
    "OPENING_STRATEGIES",
    "OPENING_STRATEGY_LABELS",
    "PSYCHOLOGY_ANALYZE",
    "PSYCHOLOGY_SYSTEM",
    "EVALUATION_EVALUATE",
    "EVALUATION_SYSTEM",
    "SCENARIO_PROMPTS",
    "MediatorStyle",
    "format_initial_intervention",
    "format_peer_intervention",
    "format_transition",
    "pick_scenario",
    "pick_scenario_optional",
    "pick_tool",
    "pick_tool_optional",
    "perspective_summary",
    "style_instruction",
]
